// Mapping des icônes FontAwesome pour éviter les imports individuels
import { 
  faPowerOff, faChevronDown, faUserLock, faBan, faClock, faCheck, 
  faStore, faHeart, faComment, faSatellite, faPaperPlane, faCloudUploadAlt,
  faSearch, faUser, faCog, faPlusSquare, faFlask, faGraduationCap, 
  faGlobeAmericas, faSlidersH, faShieldAlt, faDatabase, faTable, 
  faUnlink, faCheckCircle, faTimesCircle, faSyncAlt, faStethoscope,
  faRedo, faSpinner, faTimes, faLink, faShare, faMicrochip, faRetweet, 
  faBookmark, faCameraRetro, faExclamationTriangle, faBolt, faImages
} from '@fortawesome/free-solid-svg-icons';

export const iconMap = {
  'power-off': faPowerOff,
  'chevron-down': faChevronDown,
  'user-lock': faUserLock,
  'ban': faBan,
  'clock': faClock,
  'check': faCheck,
  'store': faStore,
  'heart': faHeart,
  'comment': faComment,
  'satellite': faSatellite,
  'paper-plane': faPaperPlane,
  'cloud-upload-alt': faCloudUploadAlt,
  'search': faSearch,
  'user': faUser,
  'cog': faCog,
  'plus-square': faPlusSquare,
  'flask': faFlask,
  'graduation-cap': faGraduationCap,
  'globe-americas': faGlobeAmericas,
  'sliders-h': faSlidersH,
  'shield-alt': faShieldAlt,
  'database': faDatabase,
  'table': faTable,
  'unlink': faUnlink,
  'check-circle': faCheckCircle,
  'times-circle': faTimesCircle,
  'sync-alt': faSyncAlt,
  'stethoscope': faStethoscope,
  'redo': faRedo,
  'spinner': faSpinner,
  'times': faTimes,
  'link': faLink,
  'share': faShare,
  'microchip': faMicrochip,
  'retweet': faRetweet,
  'bookmark': faBookmark,
  'camera-retro': faCameraRetro,
  'exclamation-triangle': faExclamationTriangle,
  'bolt': faBolt,
  'images': faImages
};
